"""add updated_at to jobs and unique constraint on matched_jobs

Revision ID: 0325f483e072
Revises: 610aad3aa4c1
Create Date: 2025-12-25 11:23:37.263866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0325f483e072'
down_revision: Union[str, Sequence[str], None] = '610aad3aa4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_matched_jobs_user_job', 'matched_jobs', ['user_id', 'job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_matched_jobs_user_job', table_name='matched_jobs')
    op.drop_column('jobs', 'updated_at')
    # ### end Alembic commands ###
