"""add salary_annual_min_max and rename salary to salary_text

Revision ID: 46e8209b4cfc
Revises: 0325f483e072
Create Date: 2025-12-25 12:33:17.506239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e8209b4cfc'
down_revision: Union[str, Sequence[str], None] = '0325f483e072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary_text', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('salary_annual_min', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('salary_annual_max', sa.Integer(), nullable=True))
    op.drop_column('jobs', 'salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('jobs', 'salary_annual_max')
    op.drop_column('jobs', 'salary_annual_min')
    op.drop_column('jobs', 'salary_text')
    # ### end Alembic commands ###
