"""initial schema

Revision ID: 610aad3aa4c1
Revises: 
Create Date: 2025-12-25 11:19:07.730620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610aad3aa4c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('job_board', sa.String(length=100), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_jobs_company', 'jobs', ['company'], unique=False)
    op.create_index('ix_jobs_job_board', 'jobs', ['job_board'], unique=False)
    op.create_index('ix_jobs_scraped_at', 'jobs', ['scraped_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('matched_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('matched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_matched_jobs_job_id', 'matched_jobs', ['job_id'], unique=False)
    op.create_index('ix_matched_jobs_score', 'matched_jobs', ['match_score'], unique=False)
    op.create_index('ix_matched_jobs_user_id', 'matched_jobs', ['user_id'], unique=False)
    op.create_table('user_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keywords_json', sa.JSON(), nullable=True),
    sa.Column('locations_json', sa.JSON(), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('max_salary', sa.Integer(), nullable=True),
    sa.Column('remote_preference', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_criteria_user_id', 'user_criteria', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_criteria_user_id', table_name='user_criteria')
    op.drop_table('user_criteria')
    op.drop_index('ix_matched_jobs_user_id', table_name='matched_jobs')
    op.drop_index('ix_matched_jobs_score', table_name='matched_jobs')
    op.drop_index('ix_matched_jobs_job_id', table_name='matched_jobs')
    op.drop_table('matched_jobs')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_jobs_scraped_at', table_name='jobs')
    op.drop_index('ix_jobs_job_board', table_name='jobs')
    op.drop_index('ix_jobs_company', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
