"""add fingerprint and expiration tracking

Revision ID: 8852d8c4e962
Revises: 46e8209b4cfc
Create Date: 2025-12-25 22:19:37.437268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8852d8c4e962'
down_revision: Union[str, Sequence[str], None] = '46e8209b4cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.add_column('jobs', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    op.create_index(op.f('ix_jobs_fingerprint'), 'jobs', ['fingerprint'], unique=False)
    op.create_index('ix_jobs_is_active', 'jobs', ['is_active'], unique=False)
    op.create_index('ix_jobs_last_seen_at', 'jobs', ['last_seen_at'], unique=False)

    # Backfill last_seen_at with scraped_at for existing jobs
    op.execute("UPDATE jobs SET last_seen_at = scraped_at WHERE last_seen_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_last_seen_at', table_name='jobs')
    op.drop_index('ix_jobs_is_active', table_name='jobs')
    op.drop_index(op.f('ix_jobs_fingerprint'), table_name='jobs')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'last_seen_at')
    op.drop_column('jobs', 'fingerprint')
    # ### end Alembic commands ###
